#Layyana Junaid 23k-0056
#Lab 10 task 2

import numpy as np
import abc as ab
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv(r'C:\Users\k230056\Desktop\23k0056\ab10\heart.csv')
plt.figure(figsize=(10,8))
plt.subplot(4,4,1)
plt.grid(visible=True)
sns.histplot(df,x='age')
plt.subplot(4,4,2)
plt.grid(visible=True)
sns.histplot(df,x='sex')
plt.subplot(4,4,3)
plt.grid(visible=True)
sns.histplot(df,x='cp')
plt.subplot(4,4,4)
plt.grid(visible=True)
sns.histplot(df,x='trestbps')
plt.subplot(4,4,5)
plt.grid(visible=True)
sns.histplot(df,x='chol')
plt.subplot(4,4,6)
plt.grid(visible=True)
sns.histplot(df,x='fbs')
plt.subplot(4,4,7)
plt.grid(visible=True)
sns.histplot(df,x='restecg')
plt.subplot(4,4,8)
plt.grid(visible=True)
sns.histplot(df,x='thalach')
plt.subplot(4,4,9)
plt.grid(visible=True)
sns.histplot(df,x='exang')
plt.subplot(4,4,10)
plt.grid(visible=True)
sns.histplot(df,x='oldpeak')
plt.subplot(4,4,11)
plt.grid(visible=True)
sns.histplot(df,x='slope')
plt.subplot(4,4,12)
plt.grid(visible=True)
sns.histplot(df,x='ca')
plt.subplot(4,4,13)
plt.grid(visible=True)
sns.histplot(df,x='thal')
plt.subplot(4,4,14)
plt.grid(visible=True)
sns.histplot(df,x='target')
plt.show()
sns.heatmap(df.corr(),annot=True,cmap='Purples')
plt.show()

